### ISSUE TITLE
Issue with CleanDb method and concurrent jobs

### ISSUE THREAD

**Issue by gsas2** [greenhost/BackJob#8]
If I'm running two or more concurrent background jobs, when the first of them finishes, and I call the  finish method for it, the rest of the jobs that were in progress are deleted by the cleanDb script.

The issue is that 'end_time' field default's value is '0000-00-00 00:00:00' (this is on MySQL), and it's always smaller than DATE_SUB(NOW(), INTERVAL :history DAY).

This only happens if allBacklogDays configuration parameter is defined.

My workaround for now is to change the delete commando to:
```PHP
			$this->database->createCommand()->delete($this->tableName, 
				'end_time <> '0000-00-00 00:00:00' AND end_time < DATE_SUB(NOW(), INTERVAL :history DAY)', 
				array(
					':history' => $this->backlogDays
				));
```

**Comment by mrtndwrd** [comment]
Fixed in 0cc615a2c294eddafde6a8188c558a56b5f69e70
